apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promo-api-www
  namespace: stage-1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: promo-api.stage-1-eks-stage-ecom.altex.ro
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: promo-api
            port:
              number: 80
  ingressClassName: nginx
