---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-catalog
  namespace: stage-1
  labels:
    app.kubernetes.io/instance: catalog-api
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: catalog-api
    meta.helm.sh/release-namespace: stage-1
spec:
  provider: aws
  secretObjects:
  - secretName: api-token
    type: Opaque
    data: 
    - objectName: secret-token
      key: SECRET_TOKEN
  parameters:
    objects: |
      - objectName: catalog-api
        objectType: secretsmanager
        objectAlias: secret-token