{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catalog-api.serviceAccountName" . }}
  labels:
    {{- include "catalog-api.labels" . | nindent 4 }}
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::009570627831:role/api-token-access-catalog-api
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
