{{- if .Values.sm.enabled -}}
{{- $fullName := include "symfony.fullname" . -}}
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ template "symfony.fullname" . }}-spc-secret
spec:
  provider: aws
  secretObjects:
  {{- if eq .Values.appIs "ecom-api" }}
  - secretName: parameters.yml
    type: Opaque
    data:
    - objectName: parameters.yml
      key: parameters.yml
  parameters:
    objects: |
      - objectName: "{{ .Values.sm.arnname }}"
        objectType: secretsmanager
        objectAlias: parameters.yml
  {{- else }}
    - secretName: .env
    type: Opaque
    data:
    - objectName: env
      key: .env
  parameters:
    objects: |
      - objectName: "{{ .Values.sm.arnname }}"
        objectType: secretsmanager
        objectAlias: .env
  {{- end }}

{{- end }}