{{- if .Values.sa.enabled -}}
{{- $fullName := include "symfony.fullname" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}-sa
  labels:
    app: {{ template "symfony.fullname" . }}-www
{{- with .Values.sa.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}